#!/usr/bin/python

import sys

f = open("/var/xenrt/site-controller-fail-count")
failcount = int(f.read().strip())
f.close()

if failcount < 3:
    print "XenRT site controller OK"
    sys.exit(0)
elif failcount < 10:
    print "Xenrt site controller WARNING: failed for the last %d times" % failcount
    sys.exit(1)
else:
    print "Xenrt site controller CRITICAL: failed for the last %d times" % failcount
    sys.exit(2)
