#!/usr/bin/python

import sys

f = open("/var/xenrt/deadjobs")
jobs = f.read().strip()
f.close()

if jobs == "":
    print "XenRT dead jobs check OK"
    sys.exit(0)

else:
    print "Xenrt dead jobs check CRITICAL: jobs %s have died" % jobs
    sys.exit(2)
