#!/usr/bin/python

import urllib, time, sys, calendar
lines = [x.strip() for x in urllib.urlopen("http://xenrt.hq.xensource.com/share/control/api/job/list?filter_JOBSTATUS=running&fields=STARTED,JOBDESC,DEPS,USERID").readlines()]

longjobs = []

for l in lines:
    (job, status, datestr, desc, seq, user) = l.split("\t")
    
    if datestr.strip() != "":
        date = time.strptime(datestr.replace(" UTC", ""))

        if desc.strip() == "":
            desc = "%s - %s" % (seq.strip(), user.strip())

        if "lh" in desc.lower(): # Long Haul
            continue
        if "longhaul" in desc.lower(): # Long Haul
            continue

        length = time.time() - calendar.timegm(date)
        if length > 3600 * 24 * 5:
            longjobs.append("%s (%s)" % (job, desc))

if len(longjobs) == 0:
    print "XenRT Stuck Jobs is OK"
    sys.exit(0)

else:
    print "XenRT Stuck Jobs warning - Jobs >5 Days:\n  %s" % ("\n  ".join(longjobs))
    sys.exit(1)
