#!/usr/bin/python

import sys,os,glob,xml.dom.minidom,string

errors = []

os.environ['HOME'] = "/var/lib/nagios"
f = os.popen("xenrt slist 2>&1")
err = f.close()

if not err:
    print "XenRT command check OK"
    sys.exit(0)

else:
    print "XenRT command check CRITICAL: executing xenrt slist exitted with %d" % err
    sys.exit(2)

