#!/usr/bin/python

import requests, time, sys, calendar, xenrtapi, ConfigParser

c = ConfigParser.ConfigParser()
c.read("/var/lib/nagios/.xenrtrc")
apikey = c.get("xenrt", "apikey").strip()

xenrt = xenrtapi.XenRT(apikey=apikey)

r = requests.get("http://localhost/xenrt/api/dbchecks/ismaster")

if r.status_code != 200:
    print "Skipping check - scheduler is not master"
    sys.exit(0)

jobs = xenrt.get_jobs(status=["running"], params=True, limit=0)

longjobs = []
for jid in sorted(jobs.keys(), key=lambda x:int(x)):
    
    j = jobs[jid]

    datestr = j['params'].get("STARTED")
    desc = j['description']

    if datestr:
        date = time.strptime(datestr.replace(" UTC", ""))

        if desc.strip() == "":
            desc = "%s - %s" % (seq.strip(), user.strip())

        if "lh" in desc.lower(): # Long Haul
            continue
        if "longhaul" in desc.lower(): # Long Haul
            continue

        length = time.time() - calendar.timegm(date)
        if length > 3600 * 24 * 5:
            longjobs.append("%d (%s)" % (j['id'], desc))

if len(longjobs) == 0:
    print "XenRT Stuck Jobs is OK"
    sys.exit(0)

else:
    print "XenRT Stuck Jobs warning - Jobs >5 Days:\n  %s" % ("\n  ".join(longjobs))
    sys.exit(1)
