#!/usr/bin/python

import sys,subprocess,glob,xml.dom.minidom,string,os,re

errors = []


def checkHTTP(address,name):
    err =subprocess.call("wget -q %s --no-check-certificate -O /dev/null --tries=1" % address, shell=True)
    if err:
        errors.append("%s (%s)" % (address, name))
    return err

def getTextFromXmlNode(node):
    for n in node.childNodes:
        if n.nodeType == n.TEXT_NODE or n.nodeType == n.CDATA_SECTION_NODE:
            return n.data

paths = ["FORCE_HTTP_FETCH", "JIRA_URL", "RPM_SOURCE_HTTP", "TESTRUN_URL"]

configstr=os.popen("/usr/share/xenrt/exec/main.py --dump-config").readlines()

config = {}
r = re.compile("^(.*)='(.*)'$")
for c in configstr:
    m = r.match(c.strip())
    if m:
        config[m.group(1)] = m.group(2)

for p in paths:
    try:
        checkHTTP(config[p], p)
    except:
        pass

if len(errors) == 0:
    print "XenRT HTTP check OK"
    sys.exit(0)

else:
    print "XenRT HTTP check CRITICAL: %s" % (", ".join(map (lambda x: "%s failed" % x, errors)))
    sys.exit(2)

