#!/bin/bash

set -e -x

git checkout master
git checkout -b perf
git reset --hard

for i in `cat $1/series | grep -v '#'`
do
    echo $i
    patch -p1 < $1/$i
    for j in `grep "^+++ " $1/$i | awk '{print $2}' | cut -d "/" -f 2-`
    do
        git add $j
    done
    git commit -m "Imported patch $i"
done

git push -u origin perf
git checkout master
