#!/bin/bash

set -e -x

git checkout perf
git checkout -b $2

for i in `cat $1/series | grep "#+$2$" | grep -v "^#" | awk '{print $1}'`
do
    echo $i
    git apply --index < $1/$i
    git commit -m "Imported patch $i"
done

git push -u origin $2
git checkout perf
