#!/bin/bash

set -e -x

git checkout master
git checkout -b perf
git reset --hard

for i in `cat $1/series | grep -v '#'`
do
    echo $i
    git apply --index < $1/$i
    git commit -m "Imported patch $i"
done

git push -u origin perf
git checkout master
