#!/bin/bash

set -e -x

git checkout perf
git checkout -b $2

for i in `cat $1/series | grep "#+$2$" | grep -v "^#" | awk '{print $1}'`
do
    echo $i
    patch -p1 < $1/$i
    for j in `grep "^+++ " $1/$i | awk '{print $2}' | cut -d "/" -f 2-`
    do
        git add $j
    done
    git commit -m "Imported patch $i"
done

git push -u origin $2
git checkout perf
