#!/bin/bash

set -e -x

git checkout master
git checkout -b perf

for i in `cat $1/series | grep -v '#'`
do
    echo $i
    patch -p1 < $1/$i
    git commit -a -m "Imported patch $i"
done

git push -u origin perf
git checkout master
