#!/usr/bin/python -u

import os, time, smtplib,urllib

fromaddr = "xenrt@xensource.com"
smtp = "smtp01.ad.xensource.com"

while True:
    cmd = "xenrt list -qS %s" % os.environ['Suite run ID']
    print "Executing %s" % cmd
    jobs = os.popen(cmd).read()
    if jobs.strip() == "":
        print "Suite run complete"
        break
    print "Jobs still running at %s:" % time.ctime()
    print jobs
    time.sleep(600)

if os.environ.has_key("Email"):
    sr = eval(urllib.urlopen("%sapi/python" % os.environ['BUILD_URL']).read())
    message = "Full results at http://testrun.uk.xensource.com/report.cgi?suiterun=%s&reporttype=triagemanager" % (os.environ['Suite run ID'])
    now = time.strftime("%a, %d %b %Y %H:%M:%S +0000", time.gmtime())
    msg = ("Date: %s\r\nFrom: %s\r\nTo: %s\r\nSubject: %s complete\r\n"
           % (now, fromaddr, os.environ["Email"], sr['fullDisplayName']))
    msg = msg + "\r\n" + message

    print "Emailing:\n%s" % msg

    server = smtplib.SMTP(smtp)
    server.set_debuglevel(1)
    server.sendmail(fromaddr, os.environ["Email"].split(","), msg)
    server.quit()

