#!/usr/bin/python -u

import os,urllib,re,sys

seq = "tampacert.seq"
rev = "6.1.0-59235"
inputs = "/usr/groups/release/XenServer-6.x/XS-6.1/RTM-59235"

if os.environ['No Bonding Tests'] == "true":
    noBond = "-D SINGLE_NIC=yes"
else:
    noBond = ""

cmd = "xenrt submit -n %s -m %s,%s -D MACHINES_REQUIRED=2 -v xenserver -r %s --inputs %s --email %s -D JOBDESC=AutoCertTampa -D ALLOW_ACK_SINGLE_NIC=yes -D ACK_LOCATION=/usr/groups/xenrt/xs-auto-cert-kit.iso -D POOL_JOIN_FORCE=yes %s" % (seq, os.environ['Machine'],os.environ['Slave'],rev,inputs,os.environ['Email'], noBond)

print cmd
job = os.popen(cmd).read()
print job
result = "http://xenrt.hq.xensource.com/share/control/queue.cgi?action=frame&title=ACK%%20on%%20%s&jobs=%s" % (os.environ['Machine'],job.strip())

description = "Auto cert kit on %s, results at %s" % (os.environ['Machine'], result)

os.system("java -jar /usr/share/jenkins/WEB-INF/jenkins-cli.jar -s %s set-build-description 'Tampa Auto Cert' '%s' '%s'" % (os.environ["JENKINS_URL"], os.environ["BUILD_NUMBER"], description))
