#!/usr/bin/expect -f
#
#####################################################################
# Sample expect script for automating iLO VSP Logins with conserver #
#####################################################################
#
# Filename: /usr/local/etc/ilo-startvsp

# Hardware Supported: any server with iLO-2
# Virtual Serial Port must be configured in RBSU.
# To be useful, the operating System must be running a console on
# the VSP (Virtual Serial Port).

set send_slow {1 0.02}

expect "Login Name:"
sleep 5
send -s "xenrtd"
sleep 1
send "\r"

expect "Password:"
send -s "xensource"
sleep 1
send "\r"


expect "</>hpiLO->"
sleep 5

send -s "vsp"
sleep 1

send "\r"

exit 0

