#!/usr/bin/expect -f
#
#####################################################################
# Sample expect script for automating iLO VSP Logins with conserver #
#####################################################################
#
# Filename: /usr/local/etc/ilo-startvsp

# Hardware Supported: any server with iLO-2
# Virtual Serial Port must be configured in RBSU.
# To be useful, the operating System must be running a console on
# the VSP (Virtual Serial Port).

set send_slow {1 0.02}

expect "Please enter user name :"
sleep 5
send -s "admin"
sleep 1
send "\r"

expect "Please enter pass phrase :"
sleep 1
send -s "admin"
sleep 1
send "\r"


expect "Enter selection or (0) to quit:"
sleep 1

send -s "r"
sleep 1

expect "Do you really want to start the Console Redirection (yes/no)?"
sleep 1
send -s "yes"
sleep 1
send "\r"

exit 0

