#%RAML 0.8
---
title: XenRT API v2
baseUri: http://api-dev.xenrt.citrite.net/xenrt/apiv2
version: v2
/job:
    get:
        description: Retrieve a list of jobs
        queryParameters:
            limit:
                description: Max number of results to receive (hard limit 10000)
                type: integer
                required: false
                default: 100 if completed or removed jobs are requested, hard limit otherwise
            jobid:
                description: Get jobs matching these job IDs
                type: integer
                repeat: true
                required: false
            user:
                description: Get jobs submitted by these users
                type: string
                repeat: true
                required: false
            excludeuser:
                description: Exclude jobs submitted by these users
                type: string
                repeat: true
                required: false
            suiterun:
                description: Get jobs in these suite runs
                type: integer
                repeat: true
                required: false
            status:
                description: Get jobs matching these status values
                type: string
                enum:
                    - new
                    - running
                    - removed
                    - done
                repeat: true
            results:
                description: Whether to return the results of the testcases run by the job
                type: boolean
                default: false
            params:
                description: Whether to return all of the job parameters
                type: boolean
                default: false
        responses:
            200:
                body:
                    application/json:
    /{jobid}:
        get:
            description: Retrieve details of a job
            responses:
                200:
                    body:
                        application/json:
