# 
# XenRT: build helper program
#
# James Bulpin, January 2006
#
# Copyright (c) 2006 XenSource, Inc. All use and distribution of this
# copyrighted material is governed by and subject to terms and
# conditions as licensed by XenSource, Inc. All other rights reserved.
#

TARGET = mappedfiletest.exe

include ../config.mk 

all: $(TARGET)

$(TARGET):
	echo "This needs to be built manually at the moment"

clean:
	echo "I will not: rm -f $(TARGET)"

