# This is an empty file
# It exists to replace an autogenerated file config.py
# The autogenerated file only gets built when the build scripts are run
# Running the unit tests without building however fails due to this missing
# dependency. This replaces that module. It's actual contents are not need for
# this purpose
