#!/usr/bin/perl
#
# xenrt: Xen regression Testing
#
# How to encode argument strings for make filename
#
# (C) XenSource UK Ltd, 2005
# James Bulpin, August 2005

$str = "";

for($i = 0; defined $ARGV[$i]; $i++) {
    if ($i > 0) {
	$str.=" ";
    }
    $str.=$ARGV[$i];    
}

$str =~ s/([. %=+\/\\:])/"+".sprintf("%02x",(ord($1)))/ge;
print $str;

