#!/usr/bin/env python

import sys

def help() :
    print """
        Usage: binreplace <file input> <string> <command>

        string can be:
            BIOS_VENDOR
            BIOS_VERSION
            SYS_MANUFACTURER
            SYS_PRODUCT_NAME
            SYS_PRODUCT_VERSION
            SYS_PRODUCT_SERIAL
            OEM
        
        command can be:
            read                    reads string's current value
            write <new string>      overwrites string's current value with <new string>
        """

strings = ["BIOS_VENDOR_MARKER", "BIOS_VERSION_MARKER", "SYS_MANUFACTURER_MARKER", "SYS_PRODUCT_NAME_MARKER", "SYS_PRODUCT_VERSION_MARKER", "SYS_PRODUCT_SERIAL_MARKER", "OEM_MARKER"]

#arguments checks
if len(sys.argv) < 4 or not (sys.argv[2] + "_MARKER") in strings:
    help()
    sys.exit(1)

if sys.argv[3] == "write" and len(sys.argv) < 5 :
    help()
    sys.exit(1)

if sys.argv[3] == "write" and len(sys.argv[4]) > 64 :
    print "The new string max length is 64 chars."
    sys.exit(1)


#file editing
f = open(sys.argv[1], "r+")
buf = f.read(1)
while buf != "" :
    if buf == "#" :
        rest = f.read(63)
        rest = rest.lstrip("#")
        if rest == sys.argv[2] + "_MARKER" :
            f.seek(+1, 1)
            if sys.argv[3] == "read" :
                string = f.read(64)
                if string[0] == '#' :
                    print "The default value of this string is set during the execution of hvmloader."
                else :
                    print string
            else :
                f.write(sys.argv[4] + "\0"*(64 - len(sys.argv[4])))
            break
        else :
            if not rest in strings :
                f.seek(-63, 1)
    buf = f.read(1)
f.close()

