#!/usr/bin/python

import sys
from UcsSdk import *

fabric = sys.argv[1]
user = sys.argv[2]
password = sys.argv[3]
sp = sys.argv[4]
root = sys.argv[5]
op = sys.argv[6]

print "Sending %s to %s/%s/%s/%s/%s\n" % (op, fabric, user, password, root, sp)

handle = UcsHandle()
handle.Login(fabric, user, password)

orgObj = handle.GetManagedObject(None, None,{OrgOrg.DN:root})
lsServerObj = handle.GetManagedObject(orgObj, LsServer.ClassId(), {LsServer.NAME : sp})
lsPowerObj = handle.GetManagedObject(lsServerObj, LsPower.ClassId())
handle.SetManagedObject(lsPowerObj, LsPower.ClassId(), {LsPower.STATE : op})

handle.Logout()
