#! /bin/sh
#
# Starts/stops dibbler-client
#
### BEGIN INIT INFO
# Provides:          dibbler-server
# Required-Start:    $network $remote_fs
# Required-Stop:     $network $remote_fs
# Should-Start:      $local_fs
# Should-Stop:       $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts DHCPv6 server
# Description:       By starting dibbler-server, this host
#                    will provide IPv6 addresses and other
#                    configuration parameters to DHCPv6 clients.
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/local/sbin/dibbler-server
NAME=dibbler-server
DESC="DHCPv6 server"
DAEMON_OPTS=run
PIDFILE=/var/lib/dibbler/server.pid

test -x $DAEMON || exit 0

set -e

case "$1" in
  start)
	echo -n "Starting $DESC: "
	start-stop-daemon -S -x "$DAEMON" -o -q -b -- "$DAEMON_OPTS"
	echo "$NAME."
	;;
  stop)
	echo -n "Stopping $DESC: "
	start-stop-daemon -K -x "$DAEMON" -q -o -p "$PIDFILE"
	echo "$NAME."
	;;
  status)
	echo "Status $DESC: $NAME"
	$DAEMON status
	;;
  restart|force-reload)
	echo -n "Restarting $DESC: "
	start-stop-daemon -K -x "$DAEMON" -q -o -p "$PIDFILE"
	sleep 1
	start-stop-daemon -S -x "$DAEMON" -o -q -b -- "$DAEMON_OPTS"
	echo "$NAME."
	;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
