# 
# XenRT: build helper program
#
# James Bulpin, January 2006
#
# Copyright (c) 2006 XenSource, Inc. All use and distribution of this
# copyrighted material is governed by and subject to terms and
# conditions as licensed by XenSource, Inc. All other rights reserved.
#

all: 
	@echo Nothing to make for winwrite.

install:
	install -d ${DESTDIR}/winwrite
	install sources ${DESTDIR}/winwrite/
	install winwrite.c ${DESTDIR}/winwrite/

clean:
	@echo Nothing to clean for winwrite.
