# 
# XenRT: build helper program
#
# James Bulpin, January 2006
#
# Copyright (c) 2006 XenSource, Inc. All use and distribution of this
# copyrighted material is governed by and subject to terms and
# conditions as licensed by XenSource, Inc. All other rights reserved.
#

all: 
	@echo Nothing to make for winread.

install:
	install -d ${DESTDIR}/winread
	install sources ${DESTDIR}/winread/
	install winread.c ${DESTDIR}/winread/

clean:
	@echo Nothing to clean for winread.
